runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /remodal
  static_dir: remodal

- url: /.*
  script: index.php

- url: /admin/.*
  script: admin/index.php