runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /remodal
  static_dir: remodal

- url: /admin
  static_dir: admin

#- url: /admin.*
#  script: admin/index.php
#
#- url: /admin/.*
#  script: admin/index.php
#- url: /admin
#  script: admin/index.php

- url: /.*
  script: index.php